# -*- coding: utf-8 -*-
"""facedetection2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fhjh9mCK4qUSxpfNtuWkLoZs7bF2mOnW
"""

import os
import time
import uuid
import cv2
import tensorflow as tf
import cv2
import json
import numpy as np
from matplotlib import pyplot as plt

def load_image(x):
    byte_img = tf.io.read_file(x)
    img = tf.io.decode_jpeg(byte_img)
    return img

train_images = tf.data.Dataset.list_files('aug_data\\train\\images\\*.jpg', shuffle = False)
train_images = train_images.map(load_image)
train_images = train_images.map(lambda x: tf.image.resize(x, (120,120)))
train_images = train_images.map(lambda x: x/255)

val_images = tf.data.Dataset.list_files('aug_data\\val\\images\\*.jpg', shuffle = False)
val_images = val_images.map(load_image)
val_images = val_images.map(lambda x: tf.image.resize(x, (120,120)))
val_images = val_images.map(lambda x: x/255)

test_images = tf.data.Dataset.list_files('aug_data\\test\\images\\*.jpg', shuffle = False)
test_images = test_images.map(load_image)
test_images = test_images.map(lambda x: tf.image.resize(x, (120,120)))
test_images = test_images.map(lambda x: x/255)

train_images.as_numpy_iterator().next()

def load_labels(label_path):
    with open(label_path.numpy(), 'r', encoding = "utf-8") as f:
        label = json.load(f)

    return [label['class']], label['bbox']

train_labels = tf.data.Dataset.list_files('aug_data\\train\\labels\\*.json', shuffle = False)
train_labels = train_labels.map(lambda x: tf.py_function(load_labels, [x], [tf.uint8, tf.float16]))

val_labels = tf.data.Dataset.list_files('aug_data\\val\\labels\\*.json', shuffle = False)
val_labels = val_labels.map(lambda x: tf.py_function(load_labels, [x], [tf.uint8, tf.float16]))

test_labels = tf.data.Dataset.list_files('aug_data\\test\\labels\\*.json', shuffle = False)
test_labels = test_labels.map(lambda x: tf.py_function(load_labels, [x], [tf.uint8, tf.float16]))

train_labels.as_numpy_iterator().next()

len(train_images), len(train_labels), len(val_images), len(val_labels), len(test_images), len(test_labels)

train = tf.data.Dataset.zip((train_images, train_labels))
train = train.shuffle(5000)
train = train.batch(8)
train = train.prefetch(4)

val = tf.data.Dataset.zip((val_images, val_labels))
val = val.shuffle(5000)
val = val.batch(8)
val = val.prefetch(4)

test = tf.data.Dataset.zip((test_images, test_labels))
test = test.shuffle(5000)
test = test.batch(8)
test = test.prefetch(4)

train.as_numpy_iterator().next()[0].shape

data_samples = train.as_numpy_iterator()

res = data_samples.next()

fig, ax = plt.subplots(ncols = 4, figsize = (20,20))
for idx in range(4):
    sample_image = res[0][idx].copy()
    sample_coords = res[1][1][idx]

    cv2.rectangle(sample_image,
                  tuple(np.multiply(sample_coords[:2], [120,120]).astype(int)),
                  tuple(np.multiply(sample_coords[2:], [120,120]).astype(int)),
                  (255,0,0), 2)
    ax[idx].imshow(sample_image)

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D, Input, MaxPooling2D, Dense, Flatten, Add, GlobalMaxPooling2D, Dropout, ReLU
from tensorflow.keras.applications import VGG16

def build_model():
    input = Input(shape=(120,120,3))
    vgg = VGG16(include_top = False)(input)

    f1 = GlobalMaxPooling2D()(vgg)
    class1 = Dense(2048, activation = 'relu')(f1)
    class2 = Dense(1, activation = 'sigmoid')(class1)

    f2 = GlobalMaxPooling2D()(vgg)
    regress1 = Dense(2048, activation = 'relu')(f1)
    regress2 = Dense(4, activation = 'sigmoid')(regress1)

    facetracker = Model(inputs = input, outputs = [class2, regress2])
    return facetracker

facetracker = build_model()

facetracker.summary()

batches_per_epoch = len(train)
lr_decay = (1./0.75 - 1)/batches_per_epoch

from tensorflow.keras.optimizers import Adam
opt = Adam(learning_rate=0.0001, decay=lr_decay)

def localization_loss(y_true, yhat):
    delta_coord = tf.reduce_sum(tf.square(y_true[:,:2] - yhat[:,:2]))
    h_true = y_true[:,3] - y_true[:,1]
    w_true = y_true[:,2] - y_true[:,0]
    h_pred = yhat[:,3] - yhat[:,1]
    w_pred = yhat[:,2] - yhat[:,0]

    delta_size = tf.reduce_sum(tf.square(w_true - w_pred) + tf.square(h_true - h_pred))

    return delta_coord + delta_size

classloss = tf.keras.losses.BinaryCrossentropy()
regressloss = localization_loss

class FaceTracker(Model):
    def __init__(self, facetrack, **kwargs):
        super().__init__(**kwargs)
        self.model = facetrack

    def compile(self, opt, classloss, localizationloss, **kwargs):
        super().compile(**kwargs)
        self.closs = classloss
        self.lloss = localization_loss
        self.opt = opt

    def train_step(self, batch, **kwargs):
        X,y = batch
        with tf.GradientTape() as tape:
            classes, coords = self.model(X, training = True)

            batch_classloss = self.closs(y[0], classes)
            batch_localizationloss = self.lloss(tf.cast(y[1], tf.float32), coords)

            total_loss = batch_localizationloss + 0.5*batch_classloss
            grad = tape.gradient(total_loss, self.model.trainable_variables)

        opt.apply_gradients(zip(grad, self.model.trainable_variables))
        return {"Total_loss": total_loss, "class_loss": batch_classloss, "regress_loss":batch_localizationloss}

    def test_step(self, batch, **kwargs):
        X,y = batch

        classes, coords = self.model(X, training = True)

        batch_classloss = self.closs(y[0], classes)
        batch_localizationloss = self.lloss(tf.cast(y[1], tf.float32), coords)

        total_loss = batch_localizationloss + 0.5*batch_classloss
        return {"Total_loss": total_loss, "class_loss": batch_classloss, "regress_loss":batch_localizationloss}


    def call(self, X, **kwargs):
        return self.model(X, **kwargs)

model = FaceTracker(facetracker)

model.compile(opt, classloss, regressloss)

logdir = 'logs'

tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir = logdir)

#

class SaveEveryNEpochs(tf.keras.callbacks.Callback):
    def __init__(self, save_path, interval):
        super(SaveEveryNEpochs, self).__init__()
        self.save_path = save_path
        self.interval = interval

    def on_epoch_end(self, epoch, logs=None):
        if (epoch + 1) % self.interval == 0:
            self.model.save(f"{self.save_path}/epoch-{epoch+1}.h5")
            print(f"\nCheckpoint saved for epoch {epoch + 1}!")

# Instantiate the callback
save_every_5_epochs = SaveEveryNEpochs(save_path="custom_checkpoints", interval=5)

# Add it to the model.fit call
hist = model.fit(
    train,
    epochs=25,
    validation_data=val,
    callbacks=[tensorboard_callback, save_every_5_epochs]
)

for X, y in train.take(1):
    print("Input shape:", X.shape)
    print("Class labels shape:", y[0].shape)
    print("Bounding box labels shape:", y[1].shape)

tf.print("Predicted class shape:", classes.shape)
tf.print("Predicted bounding box shape:", coords.shape)

def train_step(self, batch, **kwargs):
    X, y = batch

    # Debug shapes
    tf.print("Input shape:", X.shape)
    tf.print("Class labels shape (y[0]):", y[0].shape)
    tf.print("Bounding box labels shape (y[1]):", y[1].shape)

    with tf.GradientTape() as tape:
        classes, coords = self.model(X, training=True)

        # Debug predictions
        tf.print("Predicted class shape:", classes.shape)
        tf.print("Predicted bounding box shape:", coords.shape)

        # Ensure shapes are compatible
        y_true_class = tf.reshape(y[0], [-1, 1])  # Reshape if necessary
        batch_classloss = self.closs(y_true_class, classes)

        y_true_coords = tf.cast(y[1], tf.float32)
        batch_localizationloss = self.lloss(y_true_coords, coords)

        total_loss = batch_localizationloss + 0.5 * batch_classloss

    grads = tape.gradient(total_loss, self.model.trainable_variables)
    self.opt.apply_gradients(zip(grads, self.model.trainable_variables))

    return {
        "Total_loss": total_loss,
        "class_loss": batch_classloss,
        "regress_loss": batch_localizationloss,
    }

def train_step(self, batch, **kwargs):
    print("train_step called")  # Debugging step
    X, y = batch
    ...

hist = model.fit(
    train,
    epochs=1,  # Keep epochs low for quick debugging
    validation_data=val,
    callbacks=[tensorboard_callback, save_every_5_epochs]
)

for images, labels in train.take(1):
    print("Image batch shape:", images.shape)         # Expected: (batch_size, 120, 120, 3)
    print("Class labels shape:", labels[0].shape)     # Expected: (batch_size, 1)
    print("Bounding box labels shape:", labels[1].shape)  # Expected: (batch_size, 4)

def preprocess_labels(class_label, bbox_label):
    class_label = tf.reshape(class_label, [1])  # Reshape to ensure proper shape for class label
    bbox_label = tf.reshape(bbox_label, [4])   # Reshape to ensure proper shape for bounding box
    return class_label, bbox_label

train_labels = train_labels.map(lambda x, y: preprocess_labels(x, y))

for images, _ in train.take(1):
    classes, coords = model.model(images, training=True)
    print("Model classification output shape:", classes.shape)  # Expected: (8, 1)
    print("Model regression output shape:", coords.shape)       # Expected: (8, 4)

facetracker.compile(
    optimizer=opt,
    loss=[tf.keras.losses.BinaryCrossentropy(), localization_loss],
    loss_weights=[0.5, 1.0]
)

hist = facetracker.fit(train.take(1), epochs=1)

for images, labels in train.take(1):
    print("Image batch shape:", images.shape)         # Expected: (batch_size, 120, 120, 3)
    print("Class labels shape (y[0]):", labels[0].shape)  # Expected: (batch_size, 1)
    print("Bounding box labels shape (y[1]):", labels[1].shape)  # Expected: (batch_size, 4)

    classes, coords = facetracker(images, training=True)
    print("Predicted class shape:", classes.shape)  # Expected: (batch_size, 1)
    print("Predicted coords shape:", coords.shape)  # Expected: (batch_size, 4)

def localization_loss(y_true, y_pred):
    # Cast both tensors to float32 to ensure compatibility
    y_true = tf.cast(y_true, tf.float32)
    y_pred = tf.cast(y_pred, tf.float32)

    delta_coord = tf.reduce_sum(tf.square(y_true[:, :2] - y_pred[:, :2]))
    h_true = y_true[:, 3] - y_true[:, 1]
    w_true = y_true[:, 2] - y_true[:, 0]
    h_pred = y_pred[:, 3] - y_pred[:, 1]
    w_pred = y_pred[:, 2] - y_pred[:, 0]

    delta_size = tf.reduce_sum(tf.square(w_true - w_pred) + tf.square(h_true - h_pred))
    return delta_coord + delta_size

loss_class = tf.keras.losses.BinaryCrossentropy()(tf.ensure_shape(y[0], [None, 1]), tf.ensure_shape(classes, [None, 1]))

for images, labels in train.take(1):
    classes, coords = facetracker(images, training=True)

    # Explicitly set shapes
    y_true_class = tf.ensure_shape(labels[0], [None, 1])
    y_true_bbox = tf.ensure_shape(labels[1], [None, 4])

    # Compute losses
    loss_class = tf.keras.losses.BinaryCrossentropy()(y_true_class, classes)
    loss_bbox = localization_loss(y_true_bbox, coords)

    print(f"Classification Loss: {loss_class.numpy()}, Localization Loss: {loss_bbox.numpy()}")

for images, labels in train.take(1):
    classes, coords = facetracker(images, training=True)

    y_true_bbox = tf.ensure_shape(labels[1], [None, 4])

    # Compute classification and localization losses
    loss_class = tf.keras.losses.BinaryCrossentropy()(labels[0], classes)
    loss_bbox = localization_loss(y_true_bbox, coords)

    print(f"Classification Loss: {loss_class.numpy()}, Localization Loss: {loss_bbox.numpy()}")

hist = facetracker.fit(
    train,
    epochs=5,
    validation_data=val,
    callbacks=[tensorboard_callback]
)

for images, labels in train.take(1):
    classes, coords = facetracker(images, training=True)

    # Debug shapes
    print("Class labels shape:", labels[0].shape)
    print("Bounding box labels shape:", labels[1].shape)
    print("Predicted class shape:", classes.shape)
    print("Predicted bounding box shape:", coords.shape)

    # Explicitly ensure shapes
    labels[0] = tf.ensure_shape(labels[0], [None, 1])
    labels[1] = tf.ensure_shape(labels[1], [None, 4])
    classes = tf.ensure_shape(classes, [None, 1])
    coords = tf.ensure_shape(coords, [None, 4])

    # Loss computation
    loss_class = tf.keras.losses.BinaryCrossentropy()(labels[0], classes)
    loss_bbox = localization_loss(labels[1], coords)

    print(f"Classification Loss: {loss_class.numpy()}, Localization Loss: {loss_bbox.numpy()}")

for images, labels in train.take(1):
    classes, coords = facetracker(images, training=True)

    # Debug shapes
    print("Class labels shape:", labels[0].shape)
    print("Bounding box labels shape:", labels[1].shape)
    print("Predicted class shape:", classes.shape)
    print("Predicted bounding box shape:", coords.shape)

    # Explicitly ensure shapes
    class_labels = tf.ensure_shape(labels[0], [None, 1])
    bbox_labels = tf.ensure_shape(labels[1], [None, 4])
    class_predictions = tf.ensure_shape(classes, [None, 1])
    bbox_predictions = tf.ensure_shape(coords, [None, 4])

    # Loss computation
    loss_class = tf.keras.losses.BinaryCrossentropy()(class_labels, class_predictions)
    loss_bbox = localization_loss(bbox_labels, bbox_predictions)

    print(f"Classification Loss: {loss_class.numpy()}, Localization Loss: {loss_bbox.numpy()}")

hist = facetracker.fit(
    train,
    epochs=5,
    validation_data=val,
    callbacks=[tensorboard_callback]
)

def preprocess_labels(class_label, bbox_label):
    class_label = tf.cast(class_label, tf.float32)  # Ensure float32
    bbox_label = tf.cast(bbox_label, tf.float32)    # Ensure float32
    return tf.reshape(class_label, [1]), tf.reshape(bbox_label, [4])  # Set static shape

train_labels = train_labels.map(lambda x, y: preprocess_labels(x, y))

train = tf.data.Dataset.zip((train_images, train_labels))
train = train.map(lambda x, y: (x, (tf.reshape(y[0], [-1, 1]), tf.reshape(y[1], [-1, 4]))))
train = train.batch(8).prefetch(4)

for images, labels in train.take(1):
    print("Image batch shape:", images.shape)         # Expected: (8, 120, 120, 3)
    print("Class labels shape (y[0]):", labels[0].shape)  # Expected: (8, 1)
    print("Bounding box labels shape (y[1]):", labels[1].shape)  # Expected: (8, 4)

facetracker.compile(
    optimizer=opt,
    loss={
        "class_output": tf.keras.losses.BinaryCrossentropy(),
        "bbox_output": localization_loss
    },
    loss_weights={"class_output": 0.5, "bbox_output": 1.0}
)

facetracker = Model(inputs=input, outputs={"class_output": class2, "bbox_output": regress2})

from tensorflow.keras.layers import Dense, GlobalMaxPooling2D
from tensorflow.keras.models import Model

def build_model():
    input = tf.keras.layers.Input(shape=(120, 120, 3))
    vgg = tf.keras.applications.VGG16(include_top=False, input_tensor=input)

    # Classification output
    f1 = GlobalMaxPooling2D()(vgg.output)
    class1 = Dense(2048, activation='relu')(f1)
    class2 = Dense(1, activation='sigmoid', name="class_output")(class1)

    # Bounding box regression output
    f2 = GlobalMaxPooling2D()(vgg.output)
    regress1 = Dense(2048, activation='relu')(f2)
    regress2 = Dense(4, activation='sigmoid', name="bbox_output")(regress1)

    # Build the model
    facetracker = Model(inputs=input, outputs={"class_output": class2, "bbox_output": regress2})
    return facetracker

# Create the model
facetracker = build_model()
facetracker.summary()

facetracker.compile(
    optimizer=opt,
    loss={
        "class_output": tf.keras.losses.BinaryCrossentropy(),
        "bbox_output": localization_loss
    },
    loss_weights={"class_output": 0.5, "bbox_output": 1.0}
)

hist = facetracker.fit(
    train,
    epochs=5,
    validation_data=val,
    callbacks=[tensorboard_callback]
)

#!/bin/bash
# Download latest models from https://github.com/ultralytics/yolov5/releases
# Usage:
#    $ bash weights/download_weights.sh

from utils.google_utils import attempt_download

for x in ['s', 'm', 'l', 'x']:
    attempt_download(f'yolov5{x}.pt')

